name: Tim James Tunes
favicon: null
layout_spectrum: 1
typography_spectrum: 0.18767
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#FF6700'
    - '#EBEBEB'
    - '#C0C0C0'
    - '#3A6EA5'
    - '#004E98'
  brandStrength: 0.6493250986095518
  lightness: 0.17290457524359226
  saturation: 0.5341246221214533
  rhythmicContrast: 0.9983497196808457
purpose: []
